version: "2"

services:
  balena-hello-world:
    labels:
      io.balena.build.description: 'Mainhelloworld'
      io.balena.build.git-url: "https://github.com/barneymc/balena-nodejs-hello-world"
    environment:
      - BUILD_DESCRIPTION="Mainhelloworld"
      - GIT_URL="https://github.com/barneymc/balena-nodejs-hello-world"
    build: .
    ports:
      - "80:80"